### ISSUE TITLE
Uncaught DeadlineExceededError in  def __call_user_callback(self):

### ISSUE THREAD

**Issue by semenko** [semenko/gmail-message-retention-reminder#8]
```
    I 11:56:25.964 URL being requested: GET https://www.googleapis.com/gmail/v1/users/xx%xx.com/threads/12285abaa5090dcc?fields=messages%2Fpayload%2Fheaders&alt=json&metadataHeaders=subject&format=metadata
    E 11:56:26.084 Traceback (most recent call last):
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 267, in Handle
          result = handler(dict(self._environ), self._StartResponse)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
          rv = self.router.dispatch(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
          return route.handler_adapter(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
          return handler.dispatch()
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
          return method(*args, **kwargs)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/main.py", line 79, in get
          warning_string = run_warning_and_save_output(send_mail=should_send_mail, **kwargs)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/main.py", line 56, in run_warning_and_save_output
          warning_response = send_warning.run(*args, **kwargs)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/retention_warning/send_warning.py", line 276, in run
          gmail_service, size_estimate, subject_list = runRetentionOnOneUser(email, date_string_before)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/retention_warning/send_warning.py", line 240, in runRetentionOnOneUser
          one_thread = retry(gmail_service.users().threads().get(**thread_params).execute)()
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/retention_warning/send_warning.py", line 78, in function_to_retry
          return func(*args, **kwargs)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/lib/oauth2client/util.py", line 137, in positional_wrapper
          return wrapped(*args, **kwargs)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/lib/googleapiclient/http.py", line 722, in execute
          body=self.body, headers=self.headers)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/lib/oauth2client/util.py", line 137, in positional_wrapper
          return wrapped(*args, **kwargs)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/lib/oauth2client/client.py", line 551, in new_request
          redirections, connection_type)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/lib/httplib2/__init__.py", line 1608, in request
          (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/lib/httplib2/__init__.py", line 1350, in _request
          (response, content) = self._conn_request(conn, request_uri, method, body, headers)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/lib/httplib2/__init__.py", line 1306, in _conn_request
          response = conn.getresponse()
        File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/gae_override/httplib.py", line 522, in getresponse
          **extra_kwargs)
        File "/base/data/home/apps/s~xx-mail-retention-warning/1.385437705830426907/lib/httplib2/__init__.py", line 1106, in fixed_fetch
          validate_certificate=validate_certificate)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 271, in fetch
          return rpc.get_result()
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
          return self.__get_result_hook(self)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/urlfetch.py", line 376, in _get_fetch_result
          rpc.check_success()
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 577, in check_success
          self.wait()
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 557, in wait
          self.__call_user_callback()
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 559, in __call_user_callback
          def __call_user_callback(self):
      DeadlineExceededError
```

**Comment by semenko** [comment]
Duplicate of #7
